"""use_timezone_aware_datetimes

Revision ID: 03ec8fb25fcd
Revises: f7a8b9c0d1e2
Create Date: 2026-06-05 16:34:31.558020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03ec8fb25fcd'
down_revision: Union[str, None] = 'f7a8b9c0d1e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_claim_adjudication_logs_claim_line_id'), 'claim_adjudication_logs', ['claim_line_id'], unique=False)
    op.alter_column('claim_lines', 'copayment_cents',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.create_foreign_key(None, 'claim_lines', 'nappi_codes', ['nappi_code_id'], ['id'])
    op.create_index(op.f('ix_copayment_rules_plan_option_id'), 'copayment_rules', ['plan_option_id'], unique=False)
    op.alter_column('discipline_codes', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.create_index(op.f('ix_discipline_codes_id'), 'discipline_codes', ['id'], unique=False)
    op.drop_constraint('uq_dispute_number', 'disputes', type_='unique')
    op.create_index(op.f('ix_formulary_nappi_code_id'), 'formulary', ['nappi_code_id'], unique=False)
    op.create_index(op.f('ix_formulary_tariff_code_id'), 'formulary', ['tariff_code_id'], unique=False)
    op.alter_column('member_condition_exclusions', 'is_pmb',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('member_condition_exclusions', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.create_index(op.f('ix_member_condition_exclusions_id'), 'member_condition_exclusions', ['id'], unique=False)
    op.create_foreign_key(None, 'member_condition_exclusions', 'underwriting_decisions', ['underwriting_decision_id'], ['id'])
    op.alter_column('members', 'late_joiner_penalty_pct',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('plan_options', 'tariff_multiplier',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'100'"))
    op.alter_column('providers', 'dispensing_license',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('providers', 'contracted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('providers', 'is_blacklisted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.create_index(op.f('ix_providers_discipline_code'), 'providers', ['discipline_code'], unique=False)
    op.drop_constraint('uq_savings_account_member', 'savings_accounts', type_='unique')
    op.create_index(op.f('ix_savings_accounts_scheme_id'), 'savings_accounts', ['scheme_id'], unique=False)
    op.drop_index('ix_scheme_themes_scheme_id', table_name='scheme_themes')
    op.create_index(op.f('ix_scheme_themes_scheme_id'), 'scheme_themes', ['scheme_id'], unique=True)
    op.create_index(op.f('ix_scheme_themes_id'), 'scheme_themes', ['id'], unique=False)
    op.alter_column('underwriting_decisions', 'has_prior_cover',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('underwriting_decisions', 'is_late_joiner',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('underwriting_decisions', 'late_joiner_penalty_pct',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('underwriting_decisions', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('underwriting_decisions', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.create_index(op.f('ix_underwriting_decisions_id'), 'underwriting_decisions', ['id'], unique=False)
    op.alter_column('user_scheme_memberships', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('user_scheme_memberships', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.create_index(op.f('ix_user_scheme_memberships_id'), 'user_scheme_memberships', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_scheme_memberships_id'), table_name='user_scheme_memberships')
    op.alter_column('user_scheme_memberships', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('user_scheme_memberships', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.drop_index(op.f('ix_underwriting_decisions_id'), table_name='underwriting_decisions')
    op.alter_column('underwriting_decisions', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('underwriting_decisions', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('underwriting_decisions', 'late_joiner_penalty_pct',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('underwriting_decisions', 'is_late_joiner',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('underwriting_decisions', 'has_prior_cover',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('ix_scheme_themes_id'), table_name='scheme_themes')
    op.drop_index(op.f('ix_scheme_themes_scheme_id'), table_name='scheme_themes')
    op.create_index('ix_scheme_themes_scheme_id', 'scheme_themes', ['scheme_id'], unique=False)
    op.drop_index(op.f('ix_savings_accounts_scheme_id'), table_name='savings_accounts')
    op.create_unique_constraint('uq_savings_account_member', 'savings_accounts', ['member_id'])
    op.drop_index(op.f('ix_providers_discipline_code'), table_name='providers')
    op.alter_column('providers', 'is_blacklisted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('providers', 'contracted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('providers', 'dispensing_license',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('plan_options', 'tariff_multiplier',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'100'"))
    op.alter_column('members', 'late_joiner_penalty_pct',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.drop_constraint(None, 'member_condition_exclusions', type_='foreignkey')
    op.drop_index(op.f('ix_member_condition_exclusions_id'), table_name='member_condition_exclusions')
    op.alter_column('member_condition_exclusions', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('member_condition_exclusions', 'is_pmb',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('ix_formulary_tariff_code_id'), table_name='formulary')
    op.drop_index(op.f('ix_formulary_nappi_code_id'), table_name='formulary')
    op.create_unique_constraint('uq_dispute_number', 'disputes', ['dispute_number'])
    op.drop_index(op.f('ix_discipline_codes_id'), table_name='discipline_codes')
    op.alter_column('discipline_codes', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.drop_index(op.f('ix_copayment_rules_plan_option_id'), table_name='copayment_rules')
    op.drop_constraint(None, 'claim_lines', type_='foreignkey')
    op.alter_column('claim_lines', 'copayment_cents',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.drop_index(op.f('ix_claim_adjudication_logs_claim_line_id'), table_name='claim_adjudication_logs')
    # ### end Alembic commands ###
