"""add_scheme_id_and_indexes_to_audit_logs

Revision ID: 755d1dd2594b
Revises: 71599f082b7b
Create Date: 2026-07-23 16:05:12.412238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '755d1dd2594b'
down_revision: Union[str, None] = '71599f082b7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('managed_care_organisations', schema=None) as batch_op:
        batch_op.drop_index('ix_managed_care_organisations_id')
        batch_op.drop_index('ix_managed_care_organisations_scheme_id')

    op.drop_table('managed_care_organisations')
    with op.batch_alter_table('brokerages', schema=None) as batch_op:
        batch_op.drop_index('ix_brokerages_id')
        batch_op.drop_index('ix_brokerages_scheme_id')

    op.drop_table('brokerages')
    with op.batch_alter_table('brokers', schema=None) as batch_op:
        batch_op.drop_index('ix_brokers_id')
        batch_op.drop_index('ix_brokers_scheme_id')

    op.drop_table('brokers')
    with op.batch_alter_table('external_auditors', schema=None) as batch_op:
        batch_op.drop_index('ix_external_auditors_id')
        batch_op.drop_index('ix_external_auditors_scheme_id')

    op.drop_table('external_auditors')
    with op.batch_alter_table('statutory_actuaries', schema=None) as batch_op:
        batch_op.drop_index('ix_statutory_actuaries_id')
        batch_op.drop_index('ix_statutory_actuaries_scheme_id')

    op.drop_table('statutory_actuaries')
    with op.batch_alter_table('member_employer_history', schema=None) as batch_op:
        batch_op.drop_index('ix_member_employer_history_employer_group_id')
        batch_op.drop_index('ix_member_employer_history_member_id')
        batch_op.drop_index('ix_member_employer_history_scheme_id')

    op.drop_table('member_employer_history')
    with op.batch_alter_table('broker_commission_scales', schema=None) as batch_op:
        batch_op.drop_index('ix_broker_commission_scales_id')
        batch_op.drop_index('ix_broker_commission_scales_scheme_id')

    op.drop_table('broker_commission_scales')
    with op.batch_alter_table('information_officers', schema=None) as batch_op:
        batch_op.drop_index('ix_information_officers_id')
        batch_op.drop_index('ix_information_officers_scheme_id')

    op.drop_table('information_officers')
    with op.batch_alter_table('broker_appointments', schema=None) as batch_op:
        batch_op.drop_index('ix_broker_appointments_id')
        batch_op.drop_index('ix_broker_appointments_scheme_id')

    op.drop_table('broker_appointments')
    with op.batch_alter_table('compliance_officers', schema=None) as batch_op:
        batch_op.drop_index('ix_compliance_officers_id')
        batch_op.drop_index('ix_compliance_officers_scheme_id')

    op.drop_table('compliance_officers')
    with op.batch_alter_table('principal_officers', schema=None) as batch_op:
        batch_op.drop_index('ix_principal_officers_id')
        batch_op.drop_index('ix_principal_officers_scheme_id')

    op.drop_table('principal_officers')
    with op.batch_alter_table('employer_groups', schema=None) as batch_op:
        batch_op.drop_index('ix_employer_groups_id')
        batch_op.drop_index('ix_employer_groups_scheme_id')

    op.drop_table('employer_groups')
    with op.batch_alter_table('administrators', schema=None) as batch_op:
        batch_op.drop_index('ix_administrators_id')
        batch_op.drop_index('ix_administrators_scheme_id')

    op.drop_table('administrators')
    with op.batch_alter_table('trustees', schema=None) as batch_op:
        batch_op.drop_index('ix_trustees_id')
        batch_op.drop_index('ix_trustees_scheme_id')

    op.drop_table('trustees')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scheme_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_scheme_id'), ['scheme_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('member_contributions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_member_contributions_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member_contributions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_member_contributions_id'))

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_scheme_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_type'))
        batch_op.drop_column('scheme_id')

    op.create_table('trustees',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('id_number', sa.VARCHAR(length=13), nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('cell_number', sa.VARCHAR(length=20), nullable=True),
    sa.Column('role_on_board', sa.VARCHAR(length=16), nullable=False),
    sa.Column('appointment_date', sa.DATE(), nullable=False),
    sa.Column('term_end_date', sa.DATE(), nullable=True),
    sa.Column('vetting_status', sa.VARCHAR(length=8), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('vetting_date', sa.DATE(), nullable=True),
    sa.Column('conflict_disclosed', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('scheme_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.Column('updated_by', sa.INTEGER(), nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.Column('deleted_by', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trustees', schema=None) as batch_op:
        batch_op.create_index('ix_trustees_scheme_id', ['scheme_id'], unique=False)
        batch_op.create_index('ix_trustees_id', ['id'], unique=False)

    op.create_table('administrators',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('company_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('accreditation_number', sa.VARCHAR(length=100), nullable=True),
    sa.Column('accreditation_expiry', sa.DATE(), nullable=True),
    sa.Column('contact_person', sa.VARCHAR(length=200), nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('physical_address', sa.TEXT(), nullable=True),
    sa.Column('cms_accreditation_status', sa.VARCHAR(length=9), server_default=sa.text("'ACTIVE'"), nullable=False),
    sa.Column('contract_start_date', sa.DATE(), nullable=True),
    sa.Column('contract_end_date', sa.DATE(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('scheme_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.Column('updated_by', sa.INTEGER(), nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.Column('deleted_by', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('administrators', schema=None) as batch_op:
        batch_op.create_index('ix_administrators_scheme_id', ['scheme_id'], unique=False)
        batch_op.create_index('ix_administrators_id', ['id'], unique=False)

    op.create_table('employer_groups',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('company_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('registration_number', sa.VARCHAR(length=50), nullable=True),
    sa.Column('contact_person', sa.VARCHAR(length=200), nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('physical_address', sa.TEXT(), nullable=True),
    sa.Column('postal_address', sa.TEXT(), nullable=True),
    sa.Column('payroll_reference', sa.VARCHAR(length=100), nullable=True),
    sa.Column('contract_start_date', sa.DATE(), nullable=True),
    sa.Column('contract_end_date', sa.DATE(), nullable=True),
    sa.Column('employee_count', sa.INTEGER(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text("'1'"), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('scheme_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.Column('updated_by', sa.INTEGER(), nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.Column('deleted_by', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employer_groups', schema=None) as batch_op:
        batch_op.create_index('ix_employer_groups_scheme_id', ['scheme_id'], unique=False)
        batch_op.create_index('ix_employer_groups_id', ['id'], unique=False)

    op.create_table('principal_officers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('id_number', sa.VARCHAR(length=13), nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('cell_number', sa.VARCHAR(length=20), nullable=True),
    sa.Column('appointment_date', sa.DATE(), nullable=False),
    sa.Column('term_end_date', sa.DATE(), nullable=True),
    sa.Column('cms_notification_date', sa.DATE(), nullable=True),
    sa.Column('qualifications', sa.TEXT(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text("'1'"), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('scheme_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.Column('updated_by', sa.INTEGER(), nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.Column('deleted_by', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('principal_officers', schema=None) as batch_op:
        batch_op.create_index('ix_principal_officers_scheme_id', ['scheme_id'], unique=False)
        batch_op.create_index('ix_principal_officers_id', ['id'], unique=False)

    op.create_table('compliance_officers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('id_number', sa.VARCHAR(length=13), nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('cell_number', sa.VARCHAR(length=20), nullable=True),
    sa.Column('appointment_date', sa.DATE(), nullable=True),
    sa.Column('term_end_date', sa.DATE(), nullable=True),
    sa.Column('qualifications', sa.TEXT(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text("'1'"), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('scheme_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.Column('updated_by', sa.INTEGER(), nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.Column('deleted_by', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('compliance_officers', schema=None) as batch_op:
        batch_op.create_index('ix_compliance_officers_scheme_id', ['scheme_id'], unique=False)
        batch_op.create_index('ix_compliance_officers_id', ['id'], unique=False)

    op.create_table('broker_appointments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('member_id', sa.INTEGER(), nullable=False),
    sa.Column('broker_id', sa.INTEGER(), nullable=False),
    sa.Column('brokerage_id', sa.INTEGER(), nullable=True),
    sa.Column('appointment_date', sa.DATE(), nullable=False),
    sa.Column('termination_date', sa.DATE(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=11), server_default=sa.text("'ACTIVE'"), nullable=False),
    sa.Column('termination_reason', sa.VARCHAR(length=255), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('scheme_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.Column('updated_by', sa.INTEGER(), nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.Column('deleted_by', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('broker_appointments', schema=None) as batch_op:
        batch_op.create_index('ix_broker_appointments_scheme_id', ['scheme_id'], unique=False)
        batch_op.create_index('ix_broker_appointments_id', ['id'], unique=False)

    op.create_table('information_officers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('id_number', sa.VARCHAR(length=13), nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('cell_number', sa.VARCHAR(length=20), nullable=True),
    sa.Column('appointment_date', sa.DATE(), nullable=True),
    sa.Column('regulator_registration_date', sa.DATE(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text("'1'"), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('scheme_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.Column('updated_by', sa.INTEGER(), nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.Column('deleted_by', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('information_officers', schema=None) as batch_op:
        batch_op.create_index('ix_information_officers_scheme_id', ['scheme_id'], unique=False)
        batch_op.create_index('ix_information_officers_id', ['id'], unique=False)

    op.create_table('broker_commission_scales',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('plan_option_id', sa.INTEGER(), nullable=True),
    sa.Column('member_type', sa.VARCHAR(length=17), nullable=False),
    sa.Column('commission_amount_cents', sa.INTEGER(), nullable=False),
    sa.Column('vat_inclusive', sa.BOOLEAN(), server_default=sa.text("'1'"), nullable=False),
    sa.Column('effective_date', sa.DATE(), nullable=False),
    sa.Column('end_date', sa.DATE(), nullable=True),
    sa.Column('regulatory_max_cents', sa.INTEGER(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('scheme_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.Column('updated_by', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('broker_commission_scales', schema=None) as batch_op:
        batch_op.create_index('ix_broker_commission_scales_scheme_id', ['scheme_id'], unique=False)
        batch_op.create_index('ix_broker_commission_scales_id', ['id'], unique=False)

    op.create_table('member_employer_history',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('scheme_id', sa.INTEGER(), nullable=False),
    sa.Column('member_id', sa.INTEGER(), nullable=False),
    sa.Column('employer_group_id', sa.INTEGER(), nullable=False),
    sa.Column('effective_date', sa.DATE(), nullable=False),
    sa.Column('end_date', sa.DATE(), nullable=True),
    sa.Column('employment_status', sa.VARCHAR(length=30), server_default=sa.text("'ACTIVE'"), nullable=False),
    sa.Column('payroll_reference', sa.VARCHAR(length=100), nullable=True),
    sa.Column('termination_reason', sa.TEXT(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.Column('updated_by', sa.INTEGER(), nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.Column('deleted_by', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('member_employer_history', schema=None) as batch_op:
        batch_op.create_index('ix_member_employer_history_scheme_id', ['scheme_id'], unique=False)
        batch_op.create_index('ix_member_employer_history_member_id', ['member_id'], unique=False)
        batch_op.create_index('ix_member_employer_history_employer_group_id', ['employer_group_id'], unique=False)

    op.create_table('statutory_actuaries',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('firm_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('assa_fellowship_number', sa.VARCHAR(length=50), nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('appointment_date', sa.DATE(), nullable=True),
    sa.Column('term_end_date', sa.DATE(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text("'1'"), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('scheme_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.Column('updated_by', sa.INTEGER(), nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.Column('deleted_by', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('statutory_actuaries', schema=None) as batch_op:
        batch_op.create_index('ix_statutory_actuaries_scheme_id', ['scheme_id'], unique=False)
        batch_op.create_index('ix_statutory_actuaries_id', ['id'], unique=False)

    op.create_table('external_auditors',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('firm_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('partner_name', sa.VARCHAR(length=200), nullable=True),
    sa.Column('irba_number', sa.VARCHAR(length=50), nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('appointment_date', sa.DATE(), nullable=True),
    sa.Column('engagement_end_date', sa.DATE(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text("'1'"), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('scheme_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.Column('updated_by', sa.INTEGER(), nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.Column('deleted_by', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('external_auditors', schema=None) as batch_op:
        batch_op.create_index('ix_external_auditors_scheme_id', ['scheme_id'], unique=False)
        batch_op.create_index('ix_external_auditors_id', ['id'], unique=False)

    op.create_table('brokers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('brokerage_id', sa.INTEGER(), nullable=True),
    sa.Column('full_name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('id_number', sa.VARCHAR(length=13), nullable=True),
    sa.Column('cms_accreditation_number', sa.VARCHAR(length=50), nullable=True),
    sa.Column('fais_representative_number', sa.VARCHAR(length=50), nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('cell_number', sa.VARCHAR(length=20), nullable=True),
    sa.Column('accreditation_status', sa.VARCHAR(length=12), server_default=sa.text("'ACTIVE'"), nullable=False),
    sa.Column('accreditation_expiry', sa.DATE(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text("'1'"), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('scheme_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.Column('updated_by', sa.INTEGER(), nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.Column('deleted_by', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('brokers', schema=None) as batch_op:
        batch_op.create_index('ix_brokers_scheme_id', ['scheme_id'], unique=False)
        batch_op.create_index('ix_brokers_id', ['id'], unique=False)

    op.create_table('brokerages',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('company_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('fsp_number', sa.VARCHAR(length=50), nullable=False),
    sa.Column('contact_person', sa.VARCHAR(length=200), nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('physical_address', sa.TEXT(), nullable=True),
    sa.Column('fsp_status', sa.VARCHAR(length=12), server_default=sa.text("'ACTIVE'"), nullable=False),
    sa.Column('fais_category', sa.VARCHAR(length=100), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text("'1'"), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('scheme_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.Column('updated_by', sa.INTEGER(), nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.Column('deleted_by', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('brokerages', schema=None) as batch_op:
        batch_op.create_index('ix_brokerages_scheme_id', ['scheme_id'], unique=False)
        batch_op.create_index('ix_brokerages_id', ['id'], unique=False)

    op.create_table('managed_care_organisations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('company_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('accreditation_number', sa.VARCHAR(length=100), nullable=True),
    sa.Column('accreditation_expiry', sa.DATE(), nullable=True),
    sa.Column('contact_person', sa.VARCHAR(length=200), nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('programme_types', sa.VARCHAR(length=500), nullable=True),
    sa.Column('accreditation_status', sa.VARCHAR(length=9), server_default=sa.text("'ACTIVE'"), nullable=False),
    sa.Column('contract_start_date', sa.DATE(), nullable=True),
    sa.Column('contract_end_date', sa.DATE(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('scheme_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.Column('updated_by', sa.INTEGER(), nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.Column('deleted_by', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('managed_care_organisations', schema=None) as batch_op:
        batch_op.create_index('ix_managed_care_organisations_scheme_id', ['scheme_id'], unique=False)
        batch_op.create_index('ix_managed_care_organisations_id', ['id'], unique=False)

    # ### end Alembic commands ###
