"""add_member_nominees

Revision ID: e12f8651d10f
Revises: 6dc4976b4d5f
Create Date: 2026-07-28 20:04:20.465716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e12f8651d10f'
down_revision: Union[str, None] = '6dc4976b4d5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member_nominees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('id_number', sa.String(length=13), nullable=False),
    sa.Column('relationship', sa.String(length=50), nullable=False),
    sa.Column('allocation_pct', sa.Integer(), nullable=False),
    sa.Column('scheme_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('member_nominees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_member_nominees_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_member_nominees_scheme_id'), ['scheme_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member_nominees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_member_nominees_scheme_id'))
        batch_op.drop_index(batch_op.f('ix_member_nominees_id'))

    op.drop_table('member_nominees')
    # ### end Alembic commands ###
