"""initial_schema

Revision ID: f113a87be4fa
Revises: 
Create Date: 2026-05-29 14:57:57.492400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f113a87be4fa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('icd10_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('is_pmb', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_icd10_codes_code'), 'icd10_codes', ['code'], unique=True)
    op.create_index(op.f('ix_icd10_codes_id'), 'icd10_codes', ['id'], unique=False)
    op.create_table('providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('practice_number', sa.String(length=50), nullable=False),
    sa.Column('discipline_code', sa.String(length=10), nullable=True),
    sa.Column('provider_type', sa.String(length=50), nullable=False),
    sa.Column('trading_name', sa.String(length=255), nullable=False),
    sa.Column('vat_number', sa.String(length=20), nullable=True),
    sa.Column('is_dsp', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_providers_id'), 'providers', ['id'], unique=False)
    op.create_index(op.f('ix_providers_practice_number'), 'providers', ['practice_number'], unique=True)
    op.create_table('rejection_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_rejection_codes_id'), 'rejection_codes', ['id'], unique=False)
    op.create_table('schemes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('registration_number', sa.String(length=100), nullable=False),
    sa.Column('cms_accreditation_number', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('registration_number')
    )
    op.create_index(op.f('ix_schemes_id'), 'schemes', ['id'], unique=False)
    op.create_table('tariff_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('nhrpl_rate', sa.Integer(), nullable=False),
    sa.Column('discipline_code', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tariff_codes_code'), 'tariff_codes', ['code'], unique=True)
    op.create_index(op.f('ix_tariff_codes_id'), 'tariff_codes', ['id'], unique=False)
    op.create_table('plan_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scheme_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('monthly_premium', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['scheme_id'], ['schemes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_options_id'), 'plan_options', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('scheme_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['scheme_id'], ['schemes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('benefit_limits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_option_id', sa.Integer(), nullable=False),
    sa.Column('benefit_category', sa.String(length=100), nullable=False),
    sa.Column('limit_type', sa.String(length=50), nullable=False),
    sa.Column('limit_value', sa.Integer(), nullable=False),
    sa.Column('applied_value', sa.Integer(), nullable=False),
    sa.Column('benefit_year', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plan_option_id'], ['plan_options.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_benefit_limits_id'), 'benefit_limits', ['id'], unique=False)
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scheme_id', sa.Integer(), nullable=False),
    sa.Column('membership_number', sa.String(length=50), nullable=False),
    sa.Column('id_number', sa.String(length=13), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('surname', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('cell_number', sa.String(length=20), nullable=True),
    sa.Column('plan_option_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('join_date', sa.Date(), nullable=False),
    sa.Column('termination_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plan_option_id'], ['plan_options.id'], ),
    sa.ForeignKeyConstraint(['scheme_id'], ['schemes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_members_id'), 'members', ['id'], unique=False)
    op.create_index(op.f('ix_members_id_number'), 'members', ['id_number'], unique=False)
    op.create_index(op.f('ix_members_membership_number'), 'members', ['membership_number'], unique=True)
    op.create_table('dependants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('relationship', sa.String(length=50), nullable=False),
    sa.Column('id_number', sa.String(length=13), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('surname', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('dependant_code', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dependants_id'), 'dependants', ['id'], unique=False)
    op.create_table('member_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('old_status', sa.String(length=20), nullable=True),
    sa.Column('new_status', sa.String(length=20), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_member_status_history_id'), 'member_status_history', ['id'], unique=False)
    op.create_table('authorisations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auth_number', sa.String(length=50), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('dependant_id', sa.Integer(), nullable=True),
    sa.Column('requesting_provider_id', sa.Integer(), nullable=False),
    sa.Column('icd10_codes', sa.Text(), nullable=True),
    sa.Column('procedure_codes', sa.Text(), nullable=True),
    sa.Column('auth_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('approved_days', sa.Integer(), nullable=True),
    sa.Column('clinical_notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['dependant_id'], ['dependants.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['requesting_provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authorisations_auth_number'), 'authorisations', ['auth_number'], unique=True)
    op.create_index(op.f('ix_authorisations_id'), 'authorisations', ['id'], unique=False)
    op.create_table('claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_number', sa.String(length=50), nullable=False),
    sa.Column('scheme_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('dependant_id', sa.Integer(), nullable=True),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('auth_number', sa.String(length=50), nullable=True),
    sa.Column('date_of_service_from', sa.Date(), nullable=False),
    sa.Column('date_of_service_to', sa.Date(), nullable=False),
    sa.Column('date_received', sa.Date(), nullable=False),
    sa.Column('claim_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('total_billed', sa.Integer(), nullable=False),
    sa.Column('total_approved', sa.Integer(), nullable=False),
    sa.Column('total_member_liability', sa.Integer(), nullable=False),
    sa.Column('total_scheme_liability', sa.Integer(), nullable=False),
    sa.Column('is_pmb', sa.Boolean(), nullable=True),
    sa.Column('adjudicated_by', sa.Integer(), nullable=True),
    sa.Column('adjudicated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['adjudicated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['dependant_id'], ['dependants.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.ForeignKeyConstraint(['scheme_id'], ['schemes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claims_claim_number'), 'claims', ['claim_number'], unique=True)
    op.create_index(op.f('ix_claims_id'), 'claims', ['id'], unique=False)
    op.create_table('authorisation_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auth_id', sa.Integer(), nullable=False),
    sa.Column('tariff_code', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('quantity_requested', sa.Integer(), nullable=False),
    sa.Column('quantity_approved', sa.Integer(), nullable=True),
    sa.Column('reason_declined', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['auth_id'], ['authorisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authorisation_lines_id'), 'authorisation_lines', ['id'], unique=False)
    op.create_table('claim_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('tariff_code', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('icd10_code', sa.String(length=20), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('billed_amount', sa.Integer(), nullable=False),
    sa.Column('approved_amount', sa.Integer(), nullable=False),
    sa.Column('nhrpl_rate', sa.Integer(), nullable=True),
    sa.Column('member_liability', sa.Integer(), nullable=False),
    sa.Column('rejection_reason_code', sa.String(length=20), nullable=True),
    sa.Column('rejection_reason_text', sa.String(length=500), nullable=True),
    sa.Column('is_pmb_line', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claim_lines_id'), 'claim_lines', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_claim_lines_id'), table_name='claim_lines')
    op.drop_table('claim_lines')
    op.drop_index(op.f('ix_authorisation_lines_id'), table_name='authorisation_lines')
    op.drop_table('authorisation_lines')
    op.drop_index(op.f('ix_claims_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_claim_number'), table_name='claims')
    op.drop_table('claims')
    op.drop_index(op.f('ix_authorisations_id'), table_name='authorisations')
    op.drop_index(op.f('ix_authorisations_auth_number'), table_name='authorisations')
    op.drop_table('authorisations')
    op.drop_index(op.f('ix_member_status_history_id'), table_name='member_status_history')
    op.drop_table('member_status_history')
    op.drop_index(op.f('ix_dependants_id'), table_name='dependants')
    op.drop_table('dependants')
    op.drop_index(op.f('ix_members_membership_number'), table_name='members')
    op.drop_index(op.f('ix_members_id_number'), table_name='members')
    op.drop_index(op.f('ix_members_id'), table_name='members')
    op.drop_table('members')
    op.drop_index(op.f('ix_benefit_limits_id'), table_name='benefit_limits')
    op.drop_table('benefit_limits')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_plan_options_id'), table_name='plan_options')
    op.drop_table('plan_options')
    op.drop_index(op.f('ix_tariff_codes_id'), table_name='tariff_codes')
    op.drop_index(op.f('ix_tariff_codes_code'), table_name='tariff_codes')
    op.drop_table('tariff_codes')
    op.drop_index(op.f('ix_schemes_id'), table_name='schemes')
    op.drop_table('schemes')
    op.drop_index(op.f('ix_rejection_codes_id'), table_name='rejection_codes')
    op.drop_table('rejection_codes')
    op.drop_index(op.f('ix_providers_practice_number'), table_name='providers')
    op.drop_index(op.f('ix_providers_id'), table_name='providers')
    op.drop_table('providers')
    op.drop_index(op.f('ix_icd10_codes_id'), table_name='icd10_codes')
    op.drop_index(op.f('ix_icd10_codes_code'), table_name='icd10_codes')
    op.drop_table('icd10_codes')
    # ### end Alembic commands ###
