from sqlalchemy import (
    Column, Integer, String, Boolean, ForeignKey, DateTime, Date, Text, UniqueConstraint
)
from sqlalchemy.orm import relationship
from datetime import datetime, timezone
from app.database import Base


class ContributionRate(Base):
    """Monthly contribution rates per plan × member type.
    All monetary values are configurable per scheme — nothing hardcoded."""
    __tablename__ = "contribution_rates"

    id = Column(Integer, primary_key=True, index=True)
    plan_option_id = Column(Integer, ForeignKey("plan_options.id"), nullable=False, index=True)
    member_type = Column(String(30), nullable=False)  # PRINCIPAL | ADULT_DEPENDANT | CHILD
    monthly_rate_cents = Column(Integer, nullable=False)
    effective_year = Column(Integer, nullable=False)

    plan_option = relationship("PlanOption", back_populates="contribution_rates")

    __table_args__ = (
        UniqueConstraint("plan_option_id", "member_type", "effective_year",
                         name="uq_contribution_rate"),
    )


class MemberContribution(Base):
    """Contribution ledger — one row per member per billing month.
    Generated by the billing run; stores a snapshot of composition and amounts at billing time."""
    __tablename__ = "member_contributions"

    id = Column(Integer, primary_key=True, index=True)
    member_id = Column(Integer, ForeignKey("members.id"), nullable=False, index=True)
    scheme_id = Column(Integer, ForeignKey("schemes.id"), nullable=False, index=True)
    billing_month = Column(Date, nullable=False)  # always day=1

    # Snapshot of composition at billing time
    principal_cents = Column(Integer, nullable=False, default=0)
    adult_dependant_count = Column(Integer, nullable=False, default=0)
    adult_dependant_cents = Column(Integer, nullable=False, default=0)
    child_count = Column(Integer, nullable=False, default=0)
    child_cents = Column(Integer, nullable=False, default=0)
    child_cap_applied = Column(Boolean, nullable=False, default=False)

    # Late-joiner penalty
    late_joiner_penalty_pct = Column(Integer, nullable=False, default=0)
    late_joiner_surcharge_cents = Column(Integer, nullable=False, default=0)

    # Totals
    amount_due_cents = Column(Integer, nullable=False, default=0)
    amount_paid_cents = Column(Integer, nullable=False, default=0)

    # Payment info
    payment_date = Column(Date, nullable=True)
    payment_reference = Column(String(100), nullable=True)

    # Status: generated | paid | partially_paid | overdue | written_off
    status = Column(String(20), nullable=False, default="generated")

    generated_at = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))
    created_at = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))
    updated_at = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc),
                        onupdate=lambda: datetime.now(timezone.utc))
    modified_date = Column(DateTime(timezone=True), nullable=True)
    modified_user = Column(Integer, ForeignKey("users.id"), nullable=True)

    member = relationship("Member", backref="contributions")
    scheme = relationship("Scheme")

    __table_args__ = (
        UniqueConstraint("member_id", "billing_month", name="uq_member_contribution"),
    )


class BenefitBalance(Base):
    """Running per-member benefit balance per category per year.
    Created on enrolment and reset each 1 January via initialise_benefit_balances()."""
    __tablename__ = "benefit_balances"

    id = Column(Integer, primary_key=True, index=True)
    member_id = Column(Integer, ForeignKey("members.id"), nullable=False, index=True)
    scheme_id = Column(Integer, ForeignKey("schemes.id"), nullable=False, index=True)
    benefit_category = Column(String(100), nullable=False)
    benefit_year = Column(Integer, nullable=False)
    opening_balance_cents = Column(Integer, nullable=False, default=0)
    used_cents = Column(Integer, nullable=False, default=0)
    reserved_cents = Column(Integer, nullable=False, default=0)  # held by in-flight auths
    visits_used = Column(Integer, nullable=False, default=0)
    last_updated = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc),
                          onupdate=lambda: datetime.now(timezone.utc))

    member = relationship("Member", back_populates="benefit_balances")

    __table_args__ = (
        UniqueConstraint("member_id", "benefit_category", "benefit_year",
                         name="uq_benefit_balance"),
    )


class SavingsAccount(Base):
    """Personal Savings Account (PSA) for PremiumPlus and MediSaver plans.
    15% of monthly contribution credited monthly via scheduled job."""
    __tablename__ = "savings_accounts"

    id = Column(Integer, primary_key=True, index=True)
    member_id = Column(Integer, ForeignKey("members.id"), nullable=False, unique=True, index=True)
    scheme_id = Column(Integer, ForeignKey("schemes.id"), nullable=False, index=True)
    balance_cents = Column(Integer, nullable=False, default=0)
    ytd_credited_cents = Column(Integer, nullable=False, default=0)
    benefit_year = Column(Integer, nullable=False)
    last_credited_date = Column(Date, nullable=True)
    created_at = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))
    updated_at = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc),
                        onupdate=lambda: datetime.now(timezone.utc))

    member = relationship("Member", back_populates="savings_account")


class CopaymentRule(Base):
    """Co-payment rules per scheme, optionally per plan.
    plan_option_id=NULL means the rule applies to ALL plans in the scheme.
    Plan-specific rule takes precedence over scheme-wide NULL rule."""
    __tablename__ = "copayment_rules"

    id = Column(Integer, primary_key=True, index=True)
    scheme_id = Column(Integer, ForeignKey("schemes.id"), nullable=False, index=True)
    plan_option_id = Column(Integer, ForeignKey("plan_options.id"), nullable=True, index=True)
    trigger = Column(String(100), nullable=False)
    # Trigger examples: NON_NETWORK_HOSPITAL, NON_DSP_ONCOLOGY, NO_PREAUTH_PENALTY,
    # NON_DSP_HIV_MEDICATION, NON_DSP_CHRONIC_RENAL_DIALYSIS, OUT_OF_FORMULARY_CHRONIC,
    # VOLUNTARY_CAESAR, HYSTERECTOMY, WISDOM_TEETH_DAY_CLINIC, etc.
    copayment_type = Column(String(20), nullable=False)  # PERCENTAGE | RAND_AMOUNT
    copayment_value = Column(Integer, nullable=False)  # pct * 100 OR rand cents
    description = Column(String(500), nullable=True)
    is_upfront = Column(Boolean, default=True)  # TRUE = paid before treatment; FALSE = penalty after
    is_active = Column(Boolean, default=True)

    plan_option = relationship("PlanOption", back_populates="copayment_rules")

    __table_args__ = (
        UniqueConstraint("scheme_id", "plan_option_id", "trigger",
                         name="uq_copayment_rule"),
    )


class ProviderNetwork(Base):
    """Maps providers to network types per scheme.
    Used by the network validator during adjudication."""
    __tablename__ = "provider_networks"

    id = Column(Integer, primary_key=True, index=True)
    provider_id = Column(Integer, ForeignKey("providers.id"), nullable=False, index=True)
    scheme_id = Column(Integer, ForeignKey("schemes.id"), nullable=False, index=True)
    network_type = Column(String(60), nullable=False)
    # Network types: PRIME_HOSPITAL, COMPACT_HOSPITAL, GP_MEDIPHILA, GP_MEDIVALUE,
    # GP_MEDIPLUS, GP_MEDICURVE, PHARMACY_DIRECT, PHARMACY_CHRONIC_DSP,
    # DENTAL_DENIS, OPTICAL_ISOLESO, ONCOLOGY_ICON, HIV_DSP, DIALYSIS_DSP,
    # PROSTHESIS_MJ4L, PROSTHESIS_ICPS, APPLIANCE_PREFERRED, SMARTCARE
    effective_from = Column(Date, nullable=False)
    effective_to = Column(Date, nullable=True)  # NULL = currently active

    provider = relationship("Provider", back_populates="network_memberships")
    scheme = relationship("Scheme")

    __table_args__ = (
        UniqueConstraint("provider_id", "scheme_id", "network_type",
                         name="uq_provider_network"),
    )


class NappiCode(Base):
    """NAPPI pharmacy product codes. Global reference data."""
    __tablename__ = "nappi_codes"

    id = Column(Integer, primary_key=True, index=True)
    nappi_code = Column(String(20), unique=True, nullable=False, index=True)
    product_name = Column(String(500), nullable=False)
    generic_name = Column(String(500), nullable=True)
    dosage_form = Column(String(100), nullable=True)
    strength = Column(String(100), nullable=True)
    schedule = Column(String(10), nullable=True)  # S0 through S6
    is_active = Column(Boolean, default=True)

    formulary_entries = relationship("Formulary", back_populates="nappi")


class Formulary(Base):
    """Formulary entries per plan × type. Drives formulary compliance in Stage 4 adjudication.
    reference_price_cents is used for generic reference pricing in Stage 7."""
    __tablename__ = "formulary"

    id = Column(Integer, primary_key=True, index=True)
    plan_option_id = Column(Integer, ForeignKey("plan_options.id"), nullable=False, index=True)
    formulary_type = Column(String(20), nullable=False)  # CHRONIC | ACUTE | ONCOLOGY | RADIOLOGY | PATHOLOGY
    nappi_code_id = Column(Integer, ForeignKey("nappi_codes.id"), nullable=True, index=True)
    tariff_code_id = Column(Integer, ForeignKey("tariff_codes.id"), nullable=True, index=True)
    cdl_condition = Column(String(100), nullable=True)  # e.g. HYPERTENSION — for chronic formulary
    is_covered = Column(Boolean, default=True)
    is_preferred = Column(Boolean, default=True)  # FALSE = generic substitution required
    reference_price_cents = Column(Integer, nullable=True)  # scheme reference price for generics
    max_quantity_per_script = Column(Integer, nullable=True)
    max_scripts_per_period = Column(Integer, nullable=True)
    period_days = Column(Integer, nullable=True)  # e.g. 30 for monthly
    copayment_if_non_formulary_pct = Column(Integer, nullable=True, default=20)
    effective_year = Column(Integer, nullable=False)

    plan_option = relationship("PlanOption", back_populates="formulary_entries")
    nappi = relationship("NappiCode", back_populates="formulary_entries")


class ChronicRegistration(Base):
    """CDL (Chronic Disease List) registration per member/dependant.
    Required for chronic benefit claims to pass Stage 3 PMB eligibility check."""
    __tablename__ = "chronic_registrations"

    id = Column(Integer, primary_key=True, index=True)
    scheme_id = Column(Integer, ForeignKey("schemes.id"), nullable=False, index=True)
    member_id = Column(Integer, ForeignKey("members.id"), nullable=False, index=True)
    dependant_id = Column(Integer, ForeignKey("dependants.id"), nullable=True)
    icd10_code_id = Column(Integer, ForeignKey("icd10_codes.id"), nullable=False)
    status = Column(String(20), nullable=False, default="PENDING")
    # PENDING | APPROVED | DECLINED | EXPIRED
    application_date = Column(Date, nullable=False)
    decision_date = Column(Date, nullable=True)
    decided_by = Column(Integer, ForeignKey("users.id"), nullable=True)
    expiry_date = Column(Date, nullable=True)  # annual renewal
    approved_medicines = Column(Text, nullable=True)  # JSON list of nappi_code_ids
    care_plan = Column(Text, nullable=True)  # JSON for DTP PMB approved services
    notes = Column(Text, nullable=True)
    is_pmb = Column(Boolean, default=True)
    created_at = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))
    updated_at = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc),
                        onupdate=lambda: datetime.now(timezone.utc))
    modified_date = Column(DateTime(timezone=True), nullable=True)
    modified_user = Column(Integer, ForeignKey("users.id"), nullable=True)

    member = relationship("Member", back_populates="chronic_registrations")
    dependant = relationship("Dependant")
    icd10 = relationship("ICD10Code")
    decided_by_user = relationship("User", foreign_keys=[decided_by])


class ClaimAdjudicationLog(Base):
    """Immutable per-stage adjudication detail log.
    Written once by run_full_adjudication(); read by GET /claims/{id}/adjudication-log."""
    __tablename__ = "claim_adjudication_logs"

    id = Column(Integer, primary_key=True, index=True)
    claim_id = Column(Integer, ForeignKey("claims.id"), nullable=False, index=True)
    claim_line_id = Column(Integer, ForeignKey("claim_lines.id"), nullable=True, index=True)
    stage = Column(Integer, nullable=False)        # 1-7
    stage_name = Column(String(50), nullable=False)  # ADMIN | INDUSTRY | PMB | CLINICAL | SCHEME | PMB_OVERRIDE | RATE_CALC
    rule_code = Column(String(20), nullable=False)   # e.g. ADM001, SCH003
    result = Column(String(20), nullable=False)      # PASS | FAIL | FLAG | INFO | OVERRIDE
    detail = Column(Text, nullable=True)             # JSON with rule-specific context
    created_at = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))

    claim = relationship("Claim", back_populates="adjudication_logs")


class Dispute(Base):
    """Dispute register per Medical Schemes Act timeline rules.
    Member has 90 days from rejection to lodge; administrator has 30 days to respond."""
    __tablename__ = "disputes"

    id = Column(Integer, primary_key=True, index=True)
    scheme_id = Column(Integer, ForeignKey("schemes.id"), nullable=False, index=True)
    dispute_number = Column(String(50), unique=True, nullable=False, index=True)
    member_id = Column(Integer, ForeignKey("members.id"), nullable=False, index=True)
    claim_id = Column(Integer, ForeignKey("claims.id"), nullable=True)
    dispute_type = Column(String(50), nullable=False)
    # CLAIM_REJECTION | BENEFIT_LIMIT | AUTHORISATION | CONTRIBUTION | OTHER
    description = Column(Text, nullable=False)
    status = Column(String(20), nullable=False, default="OPEN")
    # OPEN | UNDER_REVIEW | UPHELD | DISMISSED | ESCALATED_TO_CMS
    date_received = Column(Date, nullable=False)
    member_deadline = Column(Date, nullable=False)   # date_received + 90 days (MSA)
    admin_deadline = Column(Date, nullable=False)    # date_received + 30 days (MSA)
    resolution = Column(Text, nullable=True)
    escalated_to_cms = Column(Boolean, default=False)
    cms_reference = Column(String(100), nullable=True)
    resolved_by = Column(Integer, ForeignKey("users.id"), nullable=True)
    resolved_at = Column(DateTime(timezone=True), nullable=True)
    created_by = Column(Integer, ForeignKey("users.id"), nullable=True)
    created_at = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))
    updated_at = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc),
                        onupdate=lambda: datetime.now(timezone.utc))
    modified_date = Column(DateTime(timezone=True), nullable=True)
    modified_user = Column(Integer, ForeignKey("users.id"), nullable=True)

    member = relationship("Member", back_populates="disputes")
    claim = relationship("Claim")
    resolved_by_user = relationship("User", foreign_keys=[resolved_by])
    created_by_user = relationship("User", foreign_keys=[created_by])
