# Auto-generated by specs/scripts/generate_entity.py — refine in place.
# Catalogue entity: Employer / Group (id=50, pattern=light_crud)
# Regulatory anchor: MSA Reg.5

from datetime import datetime, timezone
from sqlalchemy import Boolean, Column, Date, DateTime, Integer, String, Text
from app.database import Base
from app.models.mixins import MultiTenant, Auditable, SoftDeletable


class EmployerGroup(Base, MultiTenant, Auditable, SoftDeletable):
    __tablename__ = "employer_groups"

    id = Column(Integer, primary_key=True, index=True)
    scheme_id = Column(Integer, nullable=False)  # logical FK -> schemes (service-layer enforced)
    company_name = Column(String(255), nullable=False)
    registration_number = Column(String(50), nullable=True)
    contact_person = Column(String(200), nullable=True)
    email = Column(String(255), nullable=False)
    phone = Column(String(20), nullable=True)
    physical_address = Column(Text, nullable=True)
    postal_address = Column(Text, nullable=True)
    payroll_reference = Column(String(100), nullable=True)
    contract_start_date = Column(Date, nullable=True)
    contract_end_date = Column(Date, nullable=True)
    employee_count = Column(Integer, nullable=True)
    is_active = Column(Boolean, nullable=False, default=True)
    notes = Column(Text, nullable=True)


class MemberEmployerHistory(Base, MultiTenant, Auditable, SoftDeletable):
    """Link table tracking member-employer relationships over time.
    A null end_date means the relationship is current."""
    __tablename__ = "member_employer_history"

    id = Column(Integer, primary_key=True, index=True)
    scheme_id = Column(Integer, nullable=False)  # logical FK -> schemes
    member_id = Column(Integer, nullable=False, index=True)  # logical FK -> members
    employer_group_id = Column(Integer, nullable=False, index=True)  # logical FK -> employer_groups
    effective_date = Column(Date, nullable=False)
    end_date = Column(Date, nullable=True)  # null = current
    employment_status = Column(String(30), nullable=False, default="ACTIVE")  # ACTIVE, RESIGNED, RETRENCHED, RETIRED, DISMISSED, DECEASED
    payroll_reference = Column(String(100), nullable=True)
    termination_reason = Column(Text, nullable=True)
    notes = Column(Text, nullable=True)
