# Auto-generated by specs/scripts/generate_entity.py — refine in place.
# Category: F. Intermediaries (Brokers)
# Entities: Brokerage, Broker, BrokerCommissionScale, BrokerAppointment

from datetime import datetime, timezone
from sqlalchemy import Boolean, Column, Date, DateTime, Integer, String, Text
from app.database import Base
from app.models.mixins import MultiTenant, Auditable, SoftDeletable


class Brokerage(Base, MultiTenant, Auditable, SoftDeletable):
    """FSCA-licensed Financial Service Provider — FAIS Act 37/2002"""
    __tablename__ = "brokerages"

    id = Column(Integer, primary_key=True, index=True)
    scheme_id = Column(Integer, nullable=False)  # logical FK -> schemes (service-layer enforced)
    company_name = Column(String(255), nullable=False)
    fsp_number = Column(String(50), nullable=False)
    contact_person = Column(String(200), nullable=True)
    email = Column(String(255), nullable=False)
    phone = Column(String(20), nullable=True)
    physical_address = Column(Text, nullable=True)
    fsp_status = Column(String(12), nullable=False, default="ACTIVE")  # allowed: ACTIVE | SUSPENDED | DEREGISTERED
    fais_category = Column(String(100), nullable=True)
    is_active = Column(Boolean, nullable=False, default=True)
    notes = Column(Text, nullable=True)


class Broker(Base, MultiTenant, Auditable, SoftDeletable):
    """Individual accredited broker / representative — FAIS / MSA s.65"""
    __tablename__ = "brokers"

    id = Column(Integer, primary_key=True, index=True)
    scheme_id = Column(Integer, nullable=False)  # logical FK -> schemes (service-layer enforced)
    brokerage_id = Column(Integer, nullable=True)  # logical FK -> brokerages (service-layer enforced)
    full_name = Column(String(200), nullable=False)
    id_number = Column(String(13), nullable=True)
    cms_accreditation_number = Column(String(50), nullable=True)
    fais_representative_number = Column(String(50), nullable=True)
    email = Column(String(255), nullable=False)
    cell_number = Column(String(20), nullable=True)
    accreditation_status = Column(String(12), nullable=False, default="ACTIVE")  # allowed: ACTIVE | SUSPENDED | LAPSED | DEREGISTERED
    accreditation_expiry = Column(Date, nullable=True)
    is_active = Column(Boolean, nullable=False, default=True)
    notes = Column(Text, nullable=True)


class BrokerCommissionScale(Base, MultiTenant, Auditable):
    """Statutory max commission per member per month — MSA Reg.28"""
    __tablename__ = "broker_commission_scales"

    id = Column(Integer, primary_key=True, index=True)
    scheme_id = Column(Integer, nullable=False)  # logical FK -> schemes (service-layer enforced)
    plan_option_id = Column(Integer, nullable=True)  # logical FK -> plan_options (service-layer enforced)
    member_type = Column(String(17), nullable=False)  # allowed: PRINCIPAL | ADULT_DEPENDANT | CHILD_DEPENDANT
    commission_amount_cents = Column(Integer, nullable=False)
    vat_inclusive = Column(Boolean, nullable=False, default=True)
    effective_date = Column(Date, nullable=False)
    end_date = Column(Date, nullable=True)
    regulatory_max_cents = Column(Integer, nullable=True)
    notes = Column(Text, nullable=True)


class BrokerAppointment(Base, MultiTenant, Auditable, SoftDeletable):
    """Member-to-broker appointment / allocation"""
    __tablename__ = "broker_appointments"

    id = Column(Integer, primary_key=True, index=True)
    scheme_id = Column(Integer, nullable=False)  # logical FK -> schemes (service-layer enforced)
    member_id = Column(Integer, nullable=False)  # logical FK -> members (service-layer enforced)
    broker_id = Column(Integer, nullable=False)  # logical FK -> brokers (service-layer enforced)
    brokerage_id = Column(Integer, nullable=True)  # logical FK -> brokerages (service-layer enforced)
    appointment_date = Column(Date, nullable=False)
    termination_date = Column(Date, nullable=True)
    status = Column(String(11), nullable=False, default="ACTIVE")  # allowed: ACTIVE | TERMINATED | TRANSFERRED
    termination_reason = Column(String(255), nullable=True)
    notes = Column(Text, nullable=True)
