# Auto-generated by specs/scripts/generate_entity.py — refine in place.
# Category: B. Scheme Governance & Operating
# Week-1 sprint entities: Trustee, Principal Officer, Administrator, MCO,
# External Auditor, Statutory Actuary, Compliance Officer, Information Officer

from datetime import datetime, timezone
from sqlalchemy import Boolean, Column, Date, DateTime, Integer, Numeric, String, Text
from app.database import Base
from app.models.mixins import MultiTenant, Auditable, SoftDeletable


class Trustee(Base, MultiTenant, Auditable, SoftDeletable):
    """Board of Trustees — MSA s.57"""
    __tablename__ = "trustees"

    id = Column(Integer, primary_key=True, index=True)
    scheme_id = Column(Integer, nullable=False)  # logical FK -> schemes (service-layer enforced)
    full_name = Column(String(200), nullable=False)
    id_number = Column(String(13), nullable=True)
    email = Column(String(255), nullable=False)
    cell_number = Column(String(20), nullable=True)
    role_on_board = Column(String(16), nullable=False)  # allowed: CHAIRPERSON | DEPUTY_CHAIR | MEMBER_ELECTED | MEMBER_APPOINTED
    appointment_date = Column(Date, nullable=False)
    term_end_date = Column(Date, nullable=True)
    vetting_status = Column(String(8), nullable=False, default="PENDING")  # allowed: PENDING | APPROVED | REJECTED
    vetting_date = Column(Date, nullable=True)
    conflict_disclosed = Column(Boolean, nullable=False, default=False)
    notes = Column(Text, nullable=True)


class PrincipalOfficer(Base, MultiTenant, Auditable, SoftDeletable):
    """Principal Officer / CEO — MSA s.57(4)"""
    __tablename__ = "principal_officers"

    id = Column(Integer, primary_key=True, index=True)
    scheme_id = Column(Integer, nullable=False)  # logical FK -> schemes (service-layer enforced)
    full_name = Column(String(200), nullable=False)
    id_number = Column(String(13), nullable=True)
    email = Column(String(255), nullable=False)
    cell_number = Column(String(20), nullable=True)
    appointment_date = Column(Date, nullable=False)
    term_end_date = Column(Date, nullable=True)
    cms_notification_date = Column(Date, nullable=True)
    qualifications = Column(Text, nullable=True)
    is_active = Column(Boolean, nullable=False, default=True)
    notes = Column(Text, nullable=True)


class Administrator(Base, MultiTenant, Auditable, SoftDeletable):
    """CMS-accredited Administrator — MSA s.58"""
    __tablename__ = "administrators"

    id = Column(Integer, primary_key=True, index=True)
    scheme_id = Column(Integer, nullable=False)  # logical FK -> schemes (service-layer enforced)
    company_name = Column(String(255), nullable=False)
    accreditation_number = Column(String(100), nullable=True)
    accreditation_expiry = Column(Date, nullable=True)
    contact_person = Column(String(200), nullable=True)
    email = Column(String(255), nullable=False)
    phone = Column(String(20), nullable=True)
    physical_address = Column(Text, nullable=True)
    cms_accreditation_status = Column(String(9), nullable=False, default="ACTIVE")  # allowed: ACTIVE | EXPIRED | SUSPENDED | PENDING
    contract_start_date = Column(Date, nullable=True)
    contract_end_date = Column(Date, nullable=True)
    notes = Column(Text, nullable=True)


class ManagedCareOrganisation(Base, MultiTenant, Auditable, SoftDeletable):
    """Managed Care Organisation — MSA Reg.15"""
    __tablename__ = "managed_care_organisations"

    id = Column(Integer, primary_key=True, index=True)
    scheme_id = Column(Integer, nullable=False)  # logical FK -> schemes (service-layer enforced)
    company_name = Column(String(255), nullable=False)
    accreditation_number = Column(String(100), nullable=True)
    accreditation_expiry = Column(Date, nullable=True)
    contact_person = Column(String(200), nullable=True)
    email = Column(String(255), nullable=False)
    phone = Column(String(20), nullable=True)
    programme_types = Column(String(500), nullable=True)
    accreditation_status = Column(String(9), nullable=False, default="ACTIVE")  # allowed: ACTIVE | EXPIRED | SUSPENDED | PENDING
    contract_start_date = Column(Date, nullable=True)
    contract_end_date = Column(Date, nullable=True)
    notes = Column(Text, nullable=True)


class ExternalAuditor(Base, MultiTenant, Auditable, SoftDeletable):
    """External Auditor — MSA s.36"""
    __tablename__ = "external_auditors"

    id = Column(Integer, primary_key=True, index=True)
    scheme_id = Column(Integer, nullable=False)  # logical FK -> schemes (service-layer enforced)
    firm_name = Column(String(255), nullable=False)
    partner_name = Column(String(200), nullable=True)
    irba_number = Column(String(50), nullable=True)
    email = Column(String(255), nullable=False)
    phone = Column(String(20), nullable=True)
    appointment_date = Column(Date, nullable=True)
    engagement_end_date = Column(Date, nullable=True)
    is_active = Column(Boolean, nullable=False, default=True)
    notes = Column(Text, nullable=True)


class StatutoryActuary(Base, MultiTenant, Auditable, SoftDeletable):
    """Statutory Actuary — MSA s.37, ASSA SAP104"""
    __tablename__ = "statutory_actuaries"

    id = Column(Integer, primary_key=True, index=True)
    scheme_id = Column(Integer, nullable=False)  # logical FK -> schemes (service-layer enforced)
    full_name = Column(String(200), nullable=False)
    firm_name = Column(String(255), nullable=True)
    assa_fellowship_number = Column(String(50), nullable=True)
    email = Column(String(255), nullable=False)
    phone = Column(String(20), nullable=True)
    appointment_date = Column(Date, nullable=True)
    term_end_date = Column(Date, nullable=True)
    is_active = Column(Boolean, nullable=False, default=True)
    notes = Column(Text, nullable=True)


class ComplianceOfficer(Base, MultiTenant, Auditable, SoftDeletable):
    """Compliance Officer — CMS Circ.38/2018"""
    __tablename__ = "compliance_officers"

    id = Column(Integer, primary_key=True, index=True)
    scheme_id = Column(Integer, nullable=False)  # logical FK -> schemes (service-layer enforced)
    full_name = Column(String(200), nullable=False)
    id_number = Column(String(13), nullable=True)
    email = Column(String(255), nullable=False)
    cell_number = Column(String(20), nullable=True)
    appointment_date = Column(Date, nullable=True)
    term_end_date = Column(Date, nullable=True)
    qualifications = Column(Text, nullable=True)
    is_active = Column(Boolean, nullable=False, default=True)
    notes = Column(Text, nullable=True)


class InformationOfficer(Base, MultiTenant, Auditable, SoftDeletable):
    """Information Officer (POPIA) — POPIA s.55-56"""
    __tablename__ = "information_officers"

    id = Column(Integer, primary_key=True, index=True)
    scheme_id = Column(Integer, nullable=False)  # logical FK -> schemes (service-layer enforced)
    full_name = Column(String(200), nullable=False)
    id_number = Column(String(13), nullable=True)
    email = Column(String(255), nullable=False)
    cell_number = Column(String(20), nullable=True)
    appointment_date = Column(Date, nullable=True)
    regulator_registration_date = Column(Date, nullable=True)
    is_active = Column(Boolean, nullable=False, default=True)
    notes = Column(Text, nullable=True)
